name: Python CI with pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checar o código do repositório
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Configurar o ambiente Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Substitua pela versão do Python que está usando

    # 3. Instalar dependências do projeto
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instala as dependências do arquivo requirements.txt, se houver
        pip install selenium pytest  # Instalando o Selenium e pytest explicitamente

    # 4. Rodar os testes com pytest
    - name: Run tests with pytest
      run: |
        pytest --maxfail=1 --disable-warnings -q  # Executa os testes com pytest
