name: Python Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest selenium

    - name: Install Firefox and geckodriver
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox xvfb
        wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
        tar -xvzf geckodriver-v0.33.0-linux64.tar.gz
        sudo mv geckodriver /usr/local/bin

    - name: Run unit tests (Pytest)
      run: |
        pytest

    - name: Run Selenium tests (Unittest)
      run: |
        Xvfb :99 & export DISPLAY=:99 && python selenium_test.py
