# -*- coding: utf-8 -*-
import unittest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException, NoAlertPresentException
from selenium.webdriver.chrome.options import Options

class AppDynamicsJob(unittest.TestCase):
    def setUp(self):
        chrome_options = Options()
        chrome_options.add_argument("--headless")  # Remove se quiser ver o navegador
        chrome_options.add_argument("--no-sandbox")
        chrome_options.add_argument("--disable-dev-shm-usage")
        
        self.driver = webdriver.Chrome(options=chrome_options)
        self.driver.implicitly_wait(30)
        self.verificationErrors = []
        self.accept_next_alert = True
    
    def test_app_dynamics_job(self):
        driver = self.driver
        driver.get("http://localhost:8081/perfil-usuario")
        
        driver.find_element(By.XPATH, "//div[@id='root']/div/div/div[3]/div/div/div[3]/div/a/div/img").click()
        driver.find_element(By.XPATH, "//div[@id='root']/div/div/div[2]/div/div/div[3]/div/a").click()
        driver.find_element(By.XPATH, "//div[@id='root']/div/div/div/div[2]/div/div/div/div[3]/div").click()
        
        campos = driver.find_elements(By.XPATH, "//input[@value='']")
        valores = ["Julia", "27", "Feminino", "165", "66", "tipo 1"]
        
        for campo, valor in zip(campos, valores):
            campo.click()
            campo.clear()
            campo.send_keys(valor)
        
        driver.find_element(By.XPATH, "//input[@value='1']").click()
        campo140 = driver.find_element(By.XPATH, "//input[@value='140']")
        campo140.clear()
        campo140.send_keys("140")
        
        driver.get("http://localhost:8081/home")
        driver.find_element(By.XPATH, "//div[@id='root']/div/div/div[2]/div[2]/div/div/div[4]").click()
        
        driver.get("http://localhost:8081/tela-registro")
        driver.find_element(By.XPATH, "//div[@id='root']/div/div/div[3]/div[2]/div/div/div[3]/div").click()
        
        driver.find_element(By.XPATH, "//input[@value='']").click()
        driver.find_element(By.XPATH, "//div[@id='root']/div/div/div[4]/div[2]/div/div/input").clear()
        driver.find_element(By.XPATH, "//div[@id='root']/div/div/div[4]/div[2]/div/div/input").send_keys("140")
        
        Select(driver.find_element(By.XPATH, "//div[@id='root']/div/div/div[4]/div[2]/div/div/div[3]/select")).select_by_visible_text("Pós-refeição")
        driver.find_element(By.XPATH, "//div[@id='root']/div/div/div[4]/div[2]/div/div/div[6]/div").click()

        self.assertEqual("Refeição de almoco salva!", self.close_alert_and_get_its_text())

        driver.get("http://localhost:8081/home")
        driver.find_element(By.XPATH, "//div[@id='root']/div/div/div[4]/div/div/div[3]/div/a/div/img").click()
        driver.get("http://localhost:8081/tela-refeicao")
        
        driver.find_element(By.XPATH, "//div[@id='root']/div/div/div[3]/div[2]/div/div/div[3]/div[2]").click()
        Select(driver.find_element(By.XPATH, "//div[@id='root']/div/div/div[4]/div[2]/div/div/select")).select_by_visible_text("Almoço")
        
        for i in range(1, 5):
            driver.find_element(By.XPATH, f"//div[@id='root']/div/div/div[4]/div[2]/div/div/div[3]/div/div[{i}]/div/div[2]/div").click()
        
        driver.find_element(By.XPATH, "//div[@id='root']/div/div/div[4]/div[2]/div/div/div[5]").click()
        
        self.assertEqual("Refeição de almoco salva!", self.close_alert_and_get_its_text())

        driver.get("http://localhost:8081/home")
        driver.find_element(By.XPATH, "//div[@id='root']/div/div/div[4]/div/div/div[3]/div/a/div/img").click()
        driver.get("http://localhost:8081/relatorio")
        driver.find_element(By.XPATH, "//div[@id='root']/div/div/div[3]/div[2]/div/div/div[3]/div[4]").click()
        
        driver.get("http://localhost:8081/home")
        driver.find_element(By.XPATH, "//div[@id='root']/div/div/div[4]/div/div/div[3]/div/a/div/img").click()
        driver.get("http://localhost:8081/editar-usuario")
        
        driver.find_element(By.XPATH, "//div[@id='root']/div/div/div[3]/div[2]/div/div/div[4]/div[2]").click()
        driver.find_element(By.XPATH, "//div[@id='root']/div/div/div[4]/div[2]/div/div/div[6]").click()
        
        driver.find_element(By.XPATH, "//div[@id='root']/div/div/div[4]/div[2]/div/div/div[3]/input").click()
        driver.find_element(By.XPATH, "//input[@value='Tipo 1']").click()
        driver.find_element(By.XPATH, "//input[@value='julia@email.com']").click()
        
        email_field = driver.find_element(By.XPATH, "//input[@value='julia.furuguem@fecaf.com.br']")
        email_field.clear()
        email_field.send_keys("julia.furuguem@fecaf.com.br")
        
        driver.find_element(By.XPATH, "//div[@id='root']/div/div/div[4]/div[2]/div/div/div[6]").click()
        
        driver.get("http://localhost:8081/home")
        driver.find_element(By.XPATH, "//div[@id='root']/div/div/div[4]/div/div/div[3]/div/a/div/img").click()
    
    def is_element_present(self, how, what):
        try:
            self.driver.find_element(how, what)
            return True
        except NoSuchElementException:
            return False

    def is_alert_present(self):
        try:
            self.driver.switch_to.alert
            return True
        except NoAlertPresentException:
            return False

    def close_alert_and_get_its_text(self):
        try:
            alert = self.driver.switch_to.alert
            alert_text = alert.text
            if self.accept_next_alert:
                alert.accept()
            else:
                alert.dismiss()
            return alert_text
        finally:
            self.accept_next_alert = True

    def tearDown(self):
        self.assertEqual([], self.verificationErrors)
        self.driver.quit()

if __name__ == "__main__":
    unittest.main()
