name: Python Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Faz o checkout do repositório
    - name: Check out the repository
      uses: actions/checkout@v3

    # 2. Configura o Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 3. Instala as dependências
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest selenium

    # 4. Instala o Firefox e o geckodriver para Selenium
    - name: Install Firefox and geckodriver
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox xvfb
        wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
        tar -xvzf geckodriver-v0.33.0-linux64.tar.gz
        sudo mv geckodriver /usr/local/bin

    # 5. Roda os testes unitários com pytest
    - name: Run unit tests (Pytest)
      run: |
        pytest

    # 6. Roda os testes com Selenium (unittest)
    - name: Run Selenium tests (Unittest)
      run: |
        # Inicia o Xvfb (navegador headless)
        Xvfb :99 & export DISPLAY=:99
        # Roda o script de testes Selenium
        python selenium_test.py  # Substitua 'selenium_test.py' pelo nome correto do seu arquivo
