name: Python CI with pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install selenium pytest

    - name: Install Firefox and GeckoDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox
        FIREFOX_VERSION=$(firefox --version | awk '{print $3}')
        wget https://github.com/mozilla/geckodriver/releases/download/v0.32.0/geckodriver-v0.32.0-linux64.tar.gz
        tar -xvzf geckodriver-v0.32.0-linux64.tar.gz
        sudo mv geckodriver /usr/local/bin/

    - name: Run tests with pytest
      run: |
        pytest --maxfail=1 --disable-warnings -q
