name: Python application

on:
  push:
    branches: 
      - main  # Ou qualquer outra branch em que você deseja rodar o workflow
  pull_request:
    branches:
      - main  # Rodar quando houver PRs para a branch principal

jobs:
  build:
    runs-on: ubuntu-latest  # Ambiente onde os testes serão executados

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Faz o checkout do código no repositório

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Versão do Python

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt  # Instalar as dependências listadas no requirements.txt

      - name: Run tests with pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q  # Executa os testes, limitando a 1 falha e desabilitando avisos
